# Generated by Django 4.2.16 on 2024-10-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
