# Generated by Django 5.1.1 on 2024-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
