# Generated by Django 4.2.16 on 2024-11-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='task_pro.task'),
        ),
    ]
