# Generated by Django 4.2.16 on 2024-11-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0002_task_dependent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Stuck', 'Stuck')], default='Pending', max_length=100),
        ),
    ]
