# Generated by Django 4.2.16 on 2024-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0002_alter_task_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Accounts-AR', 'Accounts-AR'), ('Accounts-Ap', 'Accounts-Ap'), ('Accounts-MIS', 'Accounts-MIS'), ('Accounts Manager', 'Accounts Manager'), ('MIS', 'MIS'), ('HR', 'HR'), ('Sales Admin', 'Sales Admin'), ('Zonals Managers', 'Zonals Managers'), ('Branch Manager', 'Branch Manager'), ('Employee', 'Employee'), ('IT', 'IT'), ('Sales', 'Sales')], default='Sales', max_length=100),
        ),
    ]
