# Generated by Django 5.1.1 on 2024-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0002_remove_task_completed_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
