# Generated by Django 4.2.16 on 2024-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0003_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependent_task',
        ),
        migrations.AddField(
            model_name='task',
            name='depended_on',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='struck_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
