# Generated by Django 4.2.16 on 2024-11-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0005_task_incomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='task_created_at',
        ),
    ]
