# Generated by Django 4.2.16 on 2024-11-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0007_task_stuck_time_end_at_task_task_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='depended_on',
            new_name='task_depended_on',
        ),
    ]
