# Generated by Django 4.2.16 on 2024-11-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0009_rename_struck_time_task_struck_time_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='waiting_for',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
