# Generated by Django 4.2.16 on 2024-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0010_alter_task_waiting_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='struck_time_start_at',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stuck_time_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='waiting_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='waiting_time_start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
