# Generated by Django 4.2.16 on 2024-11-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0011_alter_task_struck_time_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
