# Generated by Django 4.2.16 on 2024-11-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0012_alter_task_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='waiting_time_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
