# Generated by Django 4.2.16 on 2024-12-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0014_task_waiting_for_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='document',
        ),
        migrations.CreateModel(
            name='multi_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='task_pro.task')),
            ],
        ),
    ]
