# Generated by Django 4.2.16 on 2024-12-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0015_remove_task_document_multi_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
