# Generated by Django 4.2.16 on 2024-12-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0016_task_is_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Is_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Accounts-AR', 'Accounts-AR'), ('Accounts-Ap', 'Accounts-Ap'), ('Accounts-MIS', 'Accounts-MIS'), ('Accounts Manager', 'Accounts Manager'), ('MIS', 'MIS'), ('HR', 'HR'), ('Sales Admin', 'Sales Admin'), ('Zonals Managers', 'Zonals Managers'), ('Branch Manager', 'Branch Manager'), ('Employee', 'Employee'), ('IT', 'IT'), ('Sales', 'Sales'), ('MM Management', 'MM Management')], default='Sales', max_length=100),
        ),
    ]
