# Generated by Django 4.2.16 on 2025-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0018_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='including_sunday',
            field=models.BooleanField(default=False),
        ),
    ]
