# Generated by Django 4.2.16 on 2025-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pro', '0019_task_including_sunday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='9876543210', max_length=11),
        ),
    ]
